### ISSUE TITLE
"Pure" CSS3 2D/3D graphics/animation

### ISSUE THREAD

**Issue by ocampesato** [jQuerySF/Generative-Art-2015#10]
These CSS3 2D/3D graphics and animation samples are based solely on CSS3 (i.e., no JavaScript, HTML5 Canvas, SVG, or any toolkits):
https://github.com/ocampesato/css3-graphics

**Comment by TheAlphaNerd** [comment]
We only have space for a single installation in the bazaar at the moment. All other art will be printed.

Feel free to re-open if you can submit a print.
