### ISSUE TITLE
Interactive particle system (ideally touch based)

### ISSUE THREAD

**Issue by jsoverson** [jQuerySF/Generative-Art-2015#3]
I made [this particle system](http://jarrodoverson.com/static/demos/particleSystem/) a few years ago and was looking for an excuse to update it to use webgl and provide multitouch functionality.

If there are any decent size multi touch displays I would love to be able to do something that allows people to interact with particles using their fingers/hands.

**Comment by TheAlphaNerd** [comment]
Thanks for submitting @jsoverson 

We'll follow up very soon!

**Comment by TheAlphaNerd** [comment]
We only have space for a single installation in the bazaar at the moment. All other art will be printed.

Feel free to re-open if you can submit a print.
