### ISSUE TITLE
Hybrid GUI based on JQuery Mobile (For desktop and touchDevice)

### ISSUE THREAD

**Issue by M1C1** [jQuerySF/Generative-Art-2015#4]
For our e3m box product, I made a rework of our old GUI using jQuery Mobile with a custom layers. My goal is to have a single GUI optimized to be used on desktop and mobile devices.

Please find attached some pictures of RC version of new GUI.

Key points :
- Global Menu is always displayed if enough width. 
- All widgets are optimized to use maximum of width window.
- In edition, we can see current modified data before save to server and we can revert current changes.
- In edition, validation of input is dynamical : validation of Input A can depend of value of Input B-C
- Extension of JQM widgets with custom functionality that I need : list-view has pagination/dataTable/multiselection/..., menu buttons can have secondary button, etc...
- Integration of external library as Highcharts, etc...

![00-gui-overview-01](https://cloud.githubusercontent.com/assets/12065179/7271402/85e3228a-e8e3-11e4-9495-2ea8fb6f8fdc.png)
![00-gui-overview-02](https://cloud.githubusercontent.com/assets/12065179/7271406/85e59d80-e8e3-11e4-98c4-9733cc414023.png)
![00-gui-overview-03](https://cloud.githubusercontent.com/assets/12065179/7271407/85e5be28-e8e3-11e4-918a-6fd909ae8e35.png)
![00-gui-overview-04](https://cloud.githubusercontent.com/assets/12065179/7271403/85e40574-e8e3-11e4-9696-322bc4d40b34.png)
![02-gui-visu-chart](https://cloud.githubusercontent.com/assets/12065179/7271404/85e40678-e8e3-11e4-826e-479f507b7ce9.png)
![02-gui-visu-table](https://cloud.githubusercontent.com/assets/12065179/7271405/85e41be0-e8e3-11e4-8637-eac32e8773e0.png)
![01-gui-responsive-01a](https://cloud.githubusercontent.com/assets/12065179/7271410/85f989a8-e8e3-11e4-85db-a13b3516497b.png)
![01-gui-responsive-01b](https://cloud.githubusercontent.com/assets/12065179/7271409/85f8e9d0-e8e3-11e4-86cf-32813e1bc170.png)
![01-gui-responsive-02a](https://cloud.githubusercontent.com/assets/12065179/7271408/85f8a3c6-e8e3-11e4-97b5-09f0b33163a1.png)
![01-gui-responsive-02b](https://cloud.githubusercontent.com/assets/12065179/7271412/85faeea6-e8e3-11e4-8e92-5b1668c24399.png)
![01-gui-responsive-02c](https://cloud.githubusercontent.com/assets/12065179/7271413/85fc1682-e8e3-11e4-9270-027a29bbe2aa.png)
![01-gui-responsive-03a](https://cloud.githubusercontent.com/assets/12065179/7271411/85fa02c0-e8e3-11e4-8958-4c4d6503a055.png)
![01-gui-responsive-03b](https://cloud.githubusercontent.com/assets/12065179/7271418/8610adc2-e8e3-11e4-8ed8-f9820be7185a.png)
![01gui-responsive-01c](https://cloud.githubusercontent.com/assets/12065179/7271414/860db11c-e8e3-11e4-8b23-e8fe0dd4cb98.png)
![02-gui-visu-synoptic](https://cloud.githubusercontent.com/assets/12065179/7271416/860fbc8c-e8e3-11e4-8609-bffbd346d80f.png)
![03-gui-edition-dyn-validation-01a](https://cloud.githubusercontent.com/assets/12065179/7271419/861239f8-e8e3-11e4-8767-aee97ac84b42.png)
![03-gui-edition-dyn-validation-01b](https://cloud.githubusercontent.com/assets/12065179/7271415/860f54c2-e8e3-11e4-985f-409b678eac99.png)
![03-gui-edition-dyn-validation-02a](https://cloud.githubusercontent.com/assets/12065179/7271417/8610a7dc-e8e3-11e4-9d45-31fb80a7d6e6.png)
![03-gui-edition-dyn-validation-02b](https://cloud.githubusercontent.com/assets/12065179/7271420/86222534-e8e3-11e4-8b60-df7e095ecc62.png)
![03-gui-edition-modification](https://cloud.githubusercontent.com/assets/12065179/7271421/8626f924-e8e3-11e4-9155-01361aecf184.png)

**Comment by TheAlphaNerd** [comment]
hey @M1C1 Thank you so much for submitting.

Unfortunately this project is not exactly appropriate for the gallery. Keep up the hard work though!
