### ISSUE TITLE
Khan Academy community as a source for generated art

### ISSUE THREAD

**Issue by pamelafox** [jQuerySF/Generative-Art-2015#5]
I teach programming on KA, and students are creating generative art literally every day (with ProcessingJS). I was just reviewing a bunch of cool "recursive art" projects from the algorithms course yesterday, but they also come up with their own creations constantly. (For example, on the hotlist today: https://www.khanacademy.org/computer-programming/random-color-tile-drawer/4890714752286720)

I'm wondering if there's interest in displaying some of their generated art. I could run it as a contest and give them more constraints to make the entries have more of a theme. They adore any contests I pass their way, and I'd love getting to showcase what our community makes in places other than our office walls. :-) 

Another thing I can do is turn their art into other artifacts. I'm currently making some of it into slap bracelets and pillows, after our "Create a fabric pattern" contest.

**Comment by TheAlphaNerd** [comment]
@pamelafox this sounds awesome.

There are so many ideas that are floating around about what this could turn in to.

I am now dreaming of a room filled with thousands of slap bracelets. I think doing a belly flop into them would be both an amazing and terrible decision.

**Comment by TheAlphaNerd** [comment]
Super excited for this!
