### ISSUE TITLE
Interactive Golden Rectangles + Spiral

### ISSUE THREAD

**Issue by simshanith** [jQuerySF/Generative-Art-2015#7]
While using no JS (besides `void(0)`) I created a set of Golden Rectangles than spins and reveals the golden spiral on hover or touch.

http://codepen.io/simshanith/pen/LEGWjb

**Comment by TheAlphaNerd** [comment]
We only have space for a single installation in the bazaar at the moment. All other art will be printed.

Feel free to re-open if you can submit a print.
