### ISSUE TITLE
jQuery + CSS3 2D/3D graphics/animation

### ISSUE THREAD

**Issue by ocampesato** [jQuerySF/Generative-Art-2015#9]
Accidentally closed the original issue...

https://github.com/ocampesato/css3-graphics

Various 2D and 3D graphics and animation effects (think "swatches") based on jQuery, and an assortment of polar equations, for frivolous fun:)

**Comment by TheAlphaNerd** [comment]
We only have space for a single installation in the bazaar at the moment. All other art will be printed.

Feel free to re-open if you can submit a print.
